[package]
name = "qeds"
version = "0.1.1"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
slab = {version="0.4",features=["serde"]}
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
robust = "0.2"
serde = {version="1.0.128", features=["derive"]}
serde_json = "1.0.66"
prettytable-rs = "0.8"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
