[package]
name = "qeds"
version = "0.1.1"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
slab = "0.4"
nalgebra = "0.29"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
