[package]
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"
name = "qeds"
version = "0.2.0"

[dependencies]
getrandom = {version = "0.2", features = ["js"]}
prettytable-rs = "0.8"
rand = "0.8"
robust = "0.2"
serde = {version = "1.0.128", features = ["derive"]} #, optional = true}
serde_json = "1.0.66"
slab = {version = "0.4", features = ["serde"]}

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

# [features]
# serde = ["slab/serde"]
